### ISSUE TITLE
PreloadScene を 3 回呼ばなきゃいけないのなんで？？

### ISSUE THREAD

**Issue by youjo-tape** [gonoji/momotech#56]
todo: そのうちなんかわかったらなんとかする

**Comment by UenoMizuki** [comment]
知らない

**Comment by youjo-tape** [comment]
複数のリソースをまとめてロードする Pack というシステムがあって、これは再帰的に読み込みが可能なようだ
https://phaser.io/examples/v3/view/loader/file-pack/load-file-pack-test-4
